name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Docker-compose Up
      run: docker-compose up -d
    - name: Sleep
      run: sleep 60
    - name: Open .jar
      run: java -jar ./artifacts/aqa-shop.jar --spring.datasource.url=jdbc:postgresql://localhost:5432/db &
    - name: Sleep
      run: sleep 60
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test
      run: ./gradlew clean test --info -Ddb=jdbc:postgresql://localhost:5432/db
