name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: build
    - name: Docker-compose Up
      run: docker-compose up -d
    - name: Sleep
      run: sleep 60
    - name: Open .jar
      run: java -jar ./artifacts/aqa-shop.jar &
    - name: Sleep
      run: sleep 60
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test
      run: ./gradlew clean test --info
